HealthNet/HealthNet/urls.py
"""
HealthNet URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Route to the admin panel
    url(r'^admin/', include(admin.site.urls)),

    # Have the root URL route to the profiles app URLs
    url(r'^', include('profiles.urls')),

    # Have /appointments route to the appointments app URLs
    url(r'^appointments/', include('appointments.urls')),

    # Have /log route to the Log app URLs
    url(r'^log/', include('log.urls')),

    url(r'^messaging/', include('messaging.urls')),
]

HealthNet/log/urls.py
"""
HealthNet Log urls
"""

from django.conf.urls import url

from . import views

app_name = 'log'  # namespace

urlpatterns = [

    # The URL to the log form and log view
    url(r'^$', views.logForm, name='logForm'),

    # This URL will delete a log event with the given primary key
    url(r'^(?P<pk>[0-9]+)/delete$', views.logDelete, name='logDelete'),

    # The URL to parse a specific log request
    # url(r'^(?P<query>\w+)$', views.logParse, name='logParse'),

]

HealthNet/messaging/urls.py
"""
HealthNet Appointments urls
"""

from django.conf.urls import url
from messaging import views

app_name = 'messaging'  # namespace

urlpatterns = [
    # Url for new message JPop
    url(r'^(?P<username>\w+)/newmessage$', views.newMessage, name='newMessage'),

    # Url for view message JPop
    url(r'^(?P<username>\w+)/viewmessage/(?P<pk>[0-9]+)$', views.viewMessage, name='viewMessage'),

    # Url for a reply
    url(r'^(?P<username>\w+)/reply/(?P<pk>[0-9]+)$', views.replyMessage, name='replyMessage'),

]

HealthNet/messaging/models.py
from django.db import models

from profiles.models import HealthNetUser


class Message(models.Model):
    """
    Class to represent a message sent from one user to another.

    @class-variable subject:            Subject line of the message.
    @class-variable body:               Body of the message.
    @class-variable sender:             Sender of the message.
    @class-variable receiver:           Receiver of the message.
    @class-variable send_date_time:     Date the message was sent.
    @class-variable reply:              The reply to this message.
    @class-variable is_draft:           Bool identifying a message as a draft.
    @class-variable was_read:           Bool identifying if a received message was read.
    """

    subject = models.CharField(max_length = 200, null = True, blank = True)
    body = models.TextField()

    sender = models.ForeignKey(HealthNetUser, related_name = 'sender')
    receiver = models.ForeignKey(HealthNetUser, related_name = 'receiver')
    send_date_time = models.DateTimeField()
    reply = models.OneToOneField('self', null = True)
    was_read = models.BooleanField(default = False)

    def preview(self):
        return "{0} ...".format(self.body[0:40])

HealthNet/profiles/models.py
"""
HealthNet Profile Models
"""
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from profiles.helpers import randomFileName, randomPhotoName

'''
Hospital model

model of hospital object for doctors, nurses, and patients to be parented by

instance variables:
    name: name of hospital
    street: street string
    city: city string
    state: 2 character state code
    zipcode: string of zipcode
    phoneNumber: hospital phone number
    numVisits: The number of patient visits to this hospital

'''


class Hospital(models.Model):
    name = models.CharField(max_length=64)
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=10)
    phoneNumber = models.CharField(max_length=10)  # CSIF?
    numVisits = models.IntegerField()

    def __str__(self):
        return self.name


'''
User model

The User model represents the basic information for every Healthnet user.

instance variables:
user: A Django User model for authentication
accountType: THe type of account (patient, doctor, etc.)
isNew: Is this a brand new account that has just been created
shownTutorial: Has the profile tutorial been shown to this user
photo: A profile picture
'''


class HealthNetUser(models.Model):
    ACCOUNT_TYPE_CHOICES = (
        ('P', 'Patient'),
        ('D', 'Doctor'),
        ('A', 'Admin'),
        ('N', 'Nurse'),
    )
    user = models.OneToOneField(User)
    accountType = models.CharField(max_length=1, choices=ACCOUNT_TYPE_CHOICES, default='P')
    isNew = models.BooleanField(default=True)
    shownTutorial = models.BooleanField(default=False)
    photo = models.ImageField(upload_to=randomPhotoName, default="/static/images/profile.png")

    def __str__(self):
        return self.user.username

    @property
    def get_name(self):
        contact = self.contact_set.filter(relation='se')
        return "{0} {1}".format(contact[0].firstName, contact[0].lastName)

    def received_messages(self):
            messages = self.receiver.all()
            return sorted(messages, key=lambda m:  m.send_date_time).reverse()

#
'''
Patient model

The Patient model is a child of User and contains fields specific to a patient.

instance variables:
birthDate: The patient's date of birth
heightFeet: The feet part of a patient's height
heightInches: The inches part of a patient's height
weight: The patient's weight
insuranceCompany: The patient's insurance company
insuranceId: The patient's insurance ID
hospitalPref: The patient's prefered hospital
hospital: The hospital that the patient is currently at (can be null)
numVisits: The number of hospital visits this patient has had
'''

class Patient(HealthNetUser):
    birthDate = models.DateField()
    heightFeet = models.IntegerField()
    heightInches = models.IntegerField()
    weight = models.IntegerField()
    insuranceCompany = models.CharField(max_length=200)
    insuranceId = models.CharField(max_length=200)
    hospitalPref = models.ForeignKey(Hospital, related_name="hospitalPref", null=True, blank=True)
    hospital = models.ForeignKey(Hospital, related_name="hospital", null=True, blank=True)
    numVisits = models.IntegerField(default = 1)


    def __str__(self):
        return self.user.username

fs = FileSystemStorage(location='/media/patient_files')

class PatientFile(models.Model):
    file = models.FileField(upload_to=randomFileName)
    name = models.CharField(max_length=64)
    patient = models.ForeignKey(Patient)

    def __str__(self):
        return self.name


'''
Contact model

The Contact model contains contact information for a person.  Each User has many Contacts.

instance variables:
firstName: A contact's first name
middleInitial: A contact's middle initial
lastName: A contact's last name
phoneNumber: A contact's phone number
street: The street address at which the contact lives
city: The city in which the contact lives
state: The state in which the contact lives
zipcode: The zipcode of the area that the contact lives
relation: The user's relation to this contact
type: The type of contact this is (patient, doctor, emergency, etc.)
user: The user that this contact belongs to
'''


class Contact(models.Model):
    firstName = models.CharField(max_length=32)
    middleInitial = models.CharField(max_length=1, null=True, blank=True)
    lastName = models.CharField(max_length=64)
    phoneNumber = models.CharField(max_length=14)
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=10)
    RELATION_CHOICES = (
        ('ga', 'Guardian'),
        ('sp', 'Spouse'),
        ('fa', 'Father'),
        ('mo', 'Mother'),
        ('si', 'Sibling'),
        ('ch', 'Child'),
        ('ot', 'Other'),
        ('se', 'Self'),
    )
    relation = models.CharField(max_length=2, choices=RELATION_CHOICES)
    TYPE_CHOICES = (
        ('e', 'Emergency'),
        ('d', 'Doctor'),
        ('n', 'Nurse'),
        ('p', 'Patient'),
    )
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    user = models.ForeignKey(HealthNetUser)

    def __str__(self):
        return self.firstName

'''
Staff model

The Staff model is a child of HealthNetUser.  Any staff using the system
(doctor, nurse, admin) has a staff object associated with them.

instance variables:
hospital: The hospital that the staff member is currently working at
bio: A short biography describing the staff member
'''

class Staff(HealthNetUser):
    hospital = models.ForeignKey(Hospital)
    bio = models.TextField(null=True)

'''
Illness model

The Illness model represents any sickness/disease that a patient can have

instance variables:
name: The common name of the illness
illnessId: The ID of the illness (used for the API) (If its hooked up...)
symptoms: A list of symptoms associated with this illness
'''

class Illness(models.Model):
    name = models.CharField(max_length=128)
    illnessId = models.CharField(max_length=64)
    symptoms = models.TextField()

    def __str__(self):
        return self.name

'''
Drug model

The Drug model represents a drug that can be prescribed by the hospital

instance variables:
name: The common name of the drug
drugId: The ID of the drug (used for the API) (If its hooked up...)
usage: The description of use (ie. 200mg twice a day)
sideEffects: A list of side effects associated with the drug
illnesses: A list of illnesses that this drug treats
'''

class Drug(models.Model):
    name = models.CharField(max_length=128)
    drugId = models.CharField(max_length=64)
    usage = models.TextField()
    sideEffects = models.TextField()
    illnesses = models.ManyToManyField(Illness)

    def __str__(self):
        return self.name

class Prescription(models.Model):
    drug = models.ForeignKey(Drug)
    startDate = models.DateField()
    refills = models.IntegerField()
    dose = models.TextField()
    pharmacy = models.CharField(max_length=64)
    patient = models.ForeignKey(Patient)
    doctor = models.ForeignKey(Staff)

    def __str__(self):
        return self.drug.name

class MedicalCase(models.Model):
    title = models.CharField(max_length=64)
    caseId = models.CharField(max_length=64)
    date = models.DateField()
    notes = models.TextField(null=True, blank=True)
    ongoing = models.BooleanField(default=True)
    patient = models.ForeignKey(Patient)
    illness = models.ForeignKey(Illness)
    prescriptions = models.ManyToManyField(Prescription, blank=True)
    files = models.ManyToManyField(PatientFile, blank=True)

    def __str__(self):
        return self.caseId

HealthNet/messaging/forms.py
from django import forms

from messaging.models import *


class NewMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('receiver', 'body', 'subject',)
        widgets={
            'subject': forms.TextInput(
                attrs = {
                    'placeholder': 'Subject...',
                    'id': 'message-subject-field',
                    'required': 'true',
                    'pattern': '^[a-zA-Z0-9.\s]*$',
                }),
            'body': forms.Textarea(
                attrs = {
                    'placeholder': 'Message body...',
                    'required': 'true',
                    'id': 'message-body-field',
                }),
        }


class ViewMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('sender', 'subject', 'body')
        widgets={
            'subject': forms.TextInput(
                attrs = {
                    'id': 'message-subject',
                    'readonly': 'true',
                }),
            'body': forms.Textarea(
                attrs = {
                    'readonly': 'true',
                    'id': 'message-body',
                }),
        }

HealthNet/messaging/views.py
import json

from django.http import HttpResponse
from django.template.loader import render_to_string
from django.utils import timezone

from profiles.models import *
from .forms import *
from .models import *
from log.views import createLogEvent

def newMessage(request, username):
    if request.user.is_authenticated():
        person = request.user.healthnetuser

        if request.method == 'POST':
            message = Message()
            message.sender = person
            message.receiver = Contact.objects.get(pk=request.POST['receiver']).user
            message.body = request.POST['body']
            message.subject = request.POST['subject']
            message.send_date_time = timezone.now()

            message.save()
            createLogEvent(request.user.username, request.user.username, 21, "Message sent")

            return HttpResponse()

        else:
            form = NewMessageForm()
            mimetype = 'application/json'
            people = Contact.objects.filter(relation='se').exclude(user_id=person.id)
            html = render_to_string('messaging/ajax_new_message.html', {'form': form, 'people': people})
            res = {'html': html}
            return HttpResponse(json.dumps(res), mimetype)

def viewMessage(request, username, pk):
    if request.user.is_authenticated():
        person = request.user.healthnetuser
        message = Message.objects.get(pk=pk)
        message.was_read = True
        message.save()
        form = ViewMessageForm(instance=message)
        mimetype = 'application/json'
        html = render_to_string('messaging/ajax_message.html', {'form': form, 'message': message})
        res = {'html': html}
        return HttpResponse(json.dumps(res), mimetype)

def replyMessage(request, username, pk):
    if request.user.is_authenticated():
        person = request.user.healthnetuser
        message_reply = Message.objects.get(pk=pk)

        reply = Message()
        reply.receiver = message_reply.sender
        reply.sender = person
        reply.subject = "Re {0}".format(message_reply.subject)

        if request.method == 'POST':
            reply.body = request.POST['body']
            reply.subject = request.POST['subject']
            reply.send_date_time = timezone.now()

            reply.save()
            createLogEvent(request.user.username, request.user.username, 21, "Message sent")

            return HttpResponse()

        else:
            form = NewMessageForm(instance=reply)
            mimetype = 'application/json'
            html = render_to_string('messaging/ajax_reply.html', {'form': form, 'message': reply})
            res = {'html': html}
            return HttpResponse(json.dumps(res), mimetype)

HealthNet/messaging/templates/messaging/ajax_message.html
<div class="row">
  <div class="col-sm-12">
    <label class="form-label" for="receiver">From:</label>
      <p>{{ message.sender.get_name }}</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="form-label">{{ form.subject.label_tag }}</div>
    <div class="form-field">{{ form.subject }}</div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="form-label">{{ form.body.label_tag }}</div>
    <div class="form-field">{{ form.body }}</div>
  </div>
</div>

HealthNet/messaging/templates/messaging/ajax_new_message.html
<div class="row">
  <div class="col-sm-12">
    <label class="form-label" for="receiver">To:</label>
      <select name="receiver" required>
      <option value="">None</option>
      {% for u in people %}
      <option value="{{ u.pk }}">{% if u.user.accountType == 'D' %}Dr. {% endif %}{{ u.firstName }} {{ u.lastName }}</option>
      {% endfor %}
    </select>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="form-label">{{ form.subject.label_tag }}</div>
    <div class="form-field">{{ form.subject }}</div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="form-label">{{ form.body.label_tag }}</div>
    <div class="form-field">{{ form.body }}</div>
  </div>
</div>

HealthNet/messaging/templates/messaging/ajax_reply.html
<div class="row">
  <div class="col-sm-12">
    <label class="form-label" for="receiver">To:</label>
      <p>{{ message.receiver.get_name }}</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="form-label">{{ form.subject.label_tag }}</div>
    <div class="form-field">{{ form.subject }}</div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="form-label">{{ form.body.label_tag }}</div>
    <div class="form-field">{{ form.body }}</div>
  </div>
</div>

HealthNet/messaging/templates/messaging/message_list_item.html
<div class="col-sm-4" style="overflow-x: hidden" pk="{{ message.pk }}">
    {% if message.was_read %}
        <div id="message-display-name" pk="{{ message.pk }}">
            <p class="sender-type-read" pk="{{ message.pk }}">{{ message.sender.get_accountType_display }}:</p>
        </div>
        <div id="message-display-name" pk="{{ message.pk }}">
            <p class="sender-name-read" pk="{{ message.pk }}">{{ message.sender.get_name }}</p>
        </div>
    {% else %}
        <div id="message-display-name" pk="{{ message.pk }}">
            <p class="sender-type-unread" pk="{{ message.pk }}">{{ message.sender.get_accountType_display }}:</p>
        </div>
        <div id="message-display-name" pk="{{ message.pk }}">
            <p class="sender-name-unread" pk="{{ message.pk }}">{{ message.sender.get_name }}</p>
        </div>
    {% endif %}
</div>
<div class="col-sm-3" style="overflow-x: hidden" pk="{{ message.pk }}">
    <div id="message-display-subject" pk="{{ message.pk }}">
        {% if message.was_read %}
            <p class="sender-name-read" pk="{{ message.pk }}">{{ message.subject }}</p>
        {% else %}
            <p class="sender-name-unread" pk="{{ message.pk }}">{{ message.subject }}</p>
        {% endif %}
    </div>
</div>
<div class="col-sm-2" style="overflow-x: hidden" pk="{{ message.pk }}">
    <div id="message-display-preview" pk="{{ message.pk }}">
        <p class="message-body" style="overflow-x: hidden" pk="{{ message.pk }}">{{ message.preview }}</p>
    </div>
</div>
<div class="col-sm-3" style="overflow-clip:hidden" pk="{{ message.pk }}">
    <div id="message-display-date" pk="{{ message.pk }}">
        <p class="sender-type-read" pk="{{ message.pk }}">{{ message.send_date_time.month }}.{{ message.send_date_time.day }}  {{ message.send_date_time.time }}</p>
    </div>
</div>

HealthNet/messaging/templates/messaging/messaging_jpop.html
<!-- New Message JPop -->
<div class="edit-form" id="new-message-popup" width="50%" style="display: none;"
     jpoptitle="New Message" mtrigger="951">
    <div class="edit-form-inner">
        <form id="new-message-popup-form" class="center" action="" method="post">
            {% csrf_token %}
            <div id="new-message-content"></div>
            <div class="edit-submit">
                <input id="message-send" type="submit" value="Send"
                       class="button-gradient-red submit-btn">
            </div>
        </form>
    </div>
</div>
<!-- End New Message JPop -->

<!-- Message JPop -->
<div class="edit-form" id="view-message-popup" width="50%" style="display: none;"
     jpoptitle="View Message" mtrigger="951">
    <div class="edit-form-inner">
        <form id="view-message-popup-form" class="center" action="" method="post">
            {% csrf_token %}
            <div id="view-message-content"></div>
            <div class="edit-submit">
                <input id="message-reply" type="submit" value="Reply"
                       class="button-gradient-red submit-btn">
                <input id="message-send-reply" type="submit" value="Send Reply"
                       class="button-gradient-red submit-btn hide">
            </div>
        </form>
    </div>
</div>
<!-- End Message JPop -->

HealthNet/messaging/templates/messaging/module_message_contacts.html
<div class="profile-pane hide" id="profile-messagecontacts-pane">
    <div class="info-bubble animate-from-bottom">
      <h1>Contacts</h1>
      <div class="sep-solid-grey" style="width: 100%;"></div>
        {% for contact in contacts %}
            {% if contact.type != 'e' %}
            <div class="row messagecontact">
                <div id="search-result-photo">
                    <img width="64px" height="64px" src="{{ contact.user.photo.url }}" id="profile-pic-pic">
                </div>
                <div id="search-result-name">
                    <h3>{{ contact.user.get_accountType_display }}</h3>

                    <h1>{{ contact.firstName }}</h1>
                    <h1>{{ contact.lastName }}</h1>

                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

HealthNet/messaging/templates/messaging/module_messages.html
<div class="profile-pane hide" id="profile-messages-pane">
    <div class="info-bubble animate-from-bottom">
        <h1 id="message-inbox-h1">Inbox</h1>
        <a href="javascript:;" id="new-message-button" username="{{ hnuser.user.username }}"
        class="jpop center" popup="new-message-popup">
          <div class="profile-quick-link-button" id="new-message-btn">
            <i class="fa fa-comment"></i><p>Compose Message</p>
          </div>
        </a>
        <div class="sep-solid-grey" style="width: 100%;"></div>
        <ul id="messages-inbox">

            {% for message in received_messages %}
                <li class="message-view-link jpop center" pk="{{ message.pk }}" popup="view-message-popup">
                    <a href="javascript:;" pk="{{ message.pk }}">
                        <div class="row message-view" pk="{{ message.pk }}">
                            {% include "messaging/message_list_item.html" %}
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

HealthNet/messaging/templates/messaging/module_messages_toolbar.html
<div class="profile-pane hide" id="msg-tools">
  <div class="info-bubble animate-from-bottom" style="padding: 2px; padding-top: 4px; padding-bottom: 4px;">
    <div id="message-toolbar">
      <a href="javascript:;" id="new-message-button" username="{{ hnuser.user.username }}"
      class="jpop center" popup="new-message-popup">
        <div class="profile-quick-link-button" id="new-message-btn">
          <i class="fa fa-comment"></i><p>Compose Message</p>
        </div>
      </a>
    </div>
  </div>
</div>